options:
    # Colors
    colors:
        primary: '#46A6E9'
        secondary: '#5A5A5B'
        tertiary: '#1A58B1'
        quaternary: '#191919'
        success: '#48BB78'
        dark: '#1A202C'
        light: '#F7FAFC'

    # Site identity
    site_favicon: ~

    # Areas
    areas:
        header: >
            [section backgroundSize="original" margin="0px" padding="0px 0px 0px 0px" color="light"]
                [section backgroundSize="original" backgroundColor="#46a6e9" margin="0px" padding="5px 30px 5px 30px" color="dark"]
                    [container justify="between" align="start" margin="0 auto"]
                        Sample content
                        [my_account_link loggedOutText="Login / Register" loggedInText="My account"/]
                    [/container]
                [/section]
                [container justify="center" align="center" margin="10px auto 10px auto"]
                    [link href="/" title="NumberNine - Every good business needs a good CMS software"]
                        [image fromTitle="NumberNine Logo" alt="NumberNine - Every good business needs a good CMS software" maxWidth="581" maxHeight="131"/]
                    [/link]
                [/container]
                [container justify="center" align="start" margin="0px auto 30px auto"]
                    [menu id="2"/]
                [/container]
            [/section]
        footer: >
            [section backgroundSize="original" height="0" margin="50px 0 0 0" padding="0" color="light"]
                [section backgroundSize="original" backgroundColor="#5A5A5B" height="0" margin="0px" padding="30px" color="dark"]
                    [grid columnsCount="4"]
                        [grid_element span="2"]
                            <h3 class="mb-5"><strong>About My Website</strong></h3>
                            <p class="text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin bibendum, est nec dignissim pellentesque, arcu magna molestie mauris, nec euismod risus ipsum eu urna. Integer quis feugiat felis. Nulla ut ullamcorper tortor. Vestibulum tellus tellus, dignissim eleifend ex venenatis, vestibulum rhoncus odio.</p>
                        [/grid_element]
                        [grid_element span="1"]
                            <h3 class="mb-5"><strong>Site links</strong></h3>
                            <ul class="text-sm list-none">
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Privacy policy</a></li>
                                <li><a href="#">Terms of use</a></li>
                            </ul>
                        [/grid_element]
                        [grid_element span="1"]
                            <h3 class="mb-5"><strong>Follow us</strong></h3>
                            <ul class="text-sm list-none">
                                <li><a href="#">Facebook</a></li>
                                <li><a href="#">Twitter</a></li>
                                <li><a href="#">Instagram</a></li>
                                <li><a href="#">YouTube</a></li>
                                <li><a href="#">Pinterest</a></li>
                            </ul>
                        [/grid_element]
                    [/grid]
                [/section]
                [section container="1" backgroundSize="original" backgroundColor="#191919" height="0" margin="0px" padding="10px" color="dark"]
                    <p>&copy; My Website</p>
                [/section]
            [/section]
        blog_sidebar: >
            [categories title="Categories"]
            [recent_posts title="Recent Posts" count="10"]
